config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products do
    resources :carts, only: [:new]
  end

  resources :carts, only: [:index, :destroy]

  root to: 'pages#index'

  get "about" => 'pages#about'
  get "contact" => 'pages#contact'
  get "checkout" => 'pages#checkout'
  get "thankyou" => 'pages#thankyou'
  resources :profiles, only: [:new, :edit, :create, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :profile
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :carts, dependent: :destroy

  has_many :customers, through: :carts, source: :profile

  def self.order_by(sort_order)
    if sort_order == "Sort A-Z"
      order(title: :asc)
    elsif sort_order == "Sort Z-A"
      order(title: :desc)
    elsif sort_order == "Price low-high"
        order(price: :asc)
    elsif sort_order == "Price high-low"
        order(price: :desc)
    else
      order(created_at: :asc)
    end
  end

  def self.search(search)
    where("title ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :carts, dependent: :destroy

  has_many :cart_products, through: :carts, source: :product

  validates :first_name, :last_name, :street, :zipcode, :city, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile

  def has_profile?
   profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :authenticate_user!

  def new
    set_product_id2
    @cart = Cart.new(product: @product, profile: current_user.profile)
    respond_to do |format|
      if @cart.save
        format.html { redirect_to products_path, notice: "Product added to your cart successuflly" }
        format.json { render :index, status: :new, location: @cart }
      else
        format.html { redirect_to products_path, notice: "Product wasn't added to the cart, sorry." }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    set_product_id
    @cart = Cart.find_by(product: @product.id)
    @cart.destroy
    redirect_to carts_path, notice: "Product deleted successuflly from your cart"
  end

  # GET /carts
  # GET /carts.json
  def index
    @cart = current_user.profile.cart_products
  end

  private

  def set_product_id
    @product = Product.find(params[:id])
  end

  def set_product_id2
    @product = Product.find(params[:product_id])
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @product1 = Product.first
    @product2 = Product.second
    @product3 = Product.third
  end

  def show
  end

  def checkout
    @cart = current_user.profile.cart_products
    @profile = current_user.profile
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]


  def index
    if params[:search]
      puts "params #{params.inspect}"
      @products = Product.search(params[:search]).order("created_at DESC")
    else
      @products = Product.all.order_by(params[:sort_by])
    end
  end

  def show
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end



end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to root_path, notice: "Profile created!"
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @profile.update(profile_params)
      redirect_to root_path, notice: "Profile updated!"
    else
      render :edit
    end
  end

  private
  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :street, :zipcode, :city)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/index.html.erb
<% @sum = 0 %>
<% @quantity = 0  %>
<div class="container"><br>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4>Your Cart</h4>
    </div>
    <div class='panel-body'>
      <ol>
      <% if @cart.any? %>
        <div class="row">
          <div class="col-md-1">
          </div>
          <div class="col-md-3">
            <h4>Product</h4>
          </div>
          <div class="col-md-2">
            <h4>Price</h4>
          </div>
          <div class="col-md-2">
            <h4>Quantity</h4>
          </div>
        </div><hr></ol>
        <ol>
          <% @cart.each do |product| %>
            <% @sum += product.price %>
                <div class="row">
                  <li>
                  <div class="col-md-1">
                    <a href = "#" class = "thumbnail">
                      <%= image_tag(product.image) %>
                    </a>
                  </div>
                  <div class="col-md-3">
                    <%= product.title %>
                  </div>
                  <div class="col-md-2">
                    € <%= product.price %>
                  </div>
                  <div class="col-md-2">
                    1
                  </div>
                  <div class="col-md-1">
                    <%= link_to "", cart_path(product), method: :delete, data: {confirm: "Are you sure you want to delete this product?"}, class:"glyphicon glyphicon-remove" %>
                  </div>
                </li>
              </div>
          <% end %>
        </ol>
        <hr>
        <p class="col-xs-2">Total price: €<%= @sum %></p>
      <% else %>
        <p>Your cart is still empty</p>
      <% end %>
      </div>
  </div>
  <%= link_to "Go back to all products", products_path, class: "btn btn-default" %>

  <% if @cart.any? %>
      <%= link_to "Proceed to checkout", checkout_path, class: "btn btn-default" %>
  <% else %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookStore</title>
		<link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada|Raleway" rel="stylesheet">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'pages/navbar' %>

    <div class="container">
    <% if notice.present? %>
      <p class="alert alert-info" role="alert">
        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
        <%= notice %>
      </p>
    <% elsif alert.present? %>
      <p class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        <%= alert %>
      </p>
    <% end %>

    <%= yield %>
    <footer class="container text-center">
      <hr><br>
      Made by Ziv, Ilsmarie, Claudia, Adriana and Maressa + <%= image_tag("http://res.cloudinary.com/maressajoseph/image/upload/v1496411761/octopus1600_gsb7wn.png", :class => "cart-item") %>
      <br><br>
    </footer>

  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Street</label>
    <%= f.text_field :street, placeholder: "Street name + number", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Zip Code</label>
    <%= f.text_field :zipcode, placeholder: "Zip Code", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>City</label>
    <%= f.text_field :city, placeholder: "City", class: "form-control" %>
  </div>

  <div class="actions">
    <%= link_to "Checkout", thankyou_path, class: "btn btn-success" %>
    <%= link_to "Cancel everything", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/pages/_guest.html.erb
<li><%= link_to "Log In", new_user_session_path %></li>
<li><%= link_to "Sign Up", new_user_registration_path %></li>

app/views/pages/_navbar.html.erb
<!-- _navbar.html.erb -->
<% @sum = 0 %>
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "The Sassy Bookstore", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <% if !user_signed_in? %>
          <%= render 'pages/guest' %>
        <% elsif user_signed_in? && current_user.has_profile? %>
          <%= render 'pages/profile' %>
        <% else %>
          <%= render 'pages/user' %>
        <% end %>
      </ul>
    </div>
  </div><!--/.nav-collapse -->
</nav>

app/views/pages/_profile.html.erb
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" id="toggle-highlight" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
      (<%= current_user.profile.cart_products.count %>)
      <span class="glyphicon glyphicon-shopping-cart"></span>
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu dropdown-cart" role="menu">
      <% current_user.profile.cart_products.each do |product| %>
        <% @sum += product.price %>
        <li>
          <span class="item">
            <span class="item-left">
              <%= image_tag(product.image) %>
              <span class="item-info">
                <h5><%= product.title %></h5>
                <h6>Price: €<%= product.price %></h6>
              </span>
            </span>
            <span class="item-right">
              <%= link_to "", cart_path(product), method: :delete, data: {confirm: "Are you sure?"}, class:"glyphicon glyphicon-remove" %>
            </span>
          </span>
        </li>
        <li class="divider"></li>
      <% end %>
      <h6 class="col-xs-5"> Total price: €<%= @sum %></h6>
      <li><%= link_to "Show Cart", carts_path %></li>
    </ul>
  </li>
</ul>
<%= render 'pages/user' %>

app/views/pages/_user.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
    <%= current_user.has_profile? ? current_user.full_name : current_user.email  %> <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li role="separator" class="divider"></li>
    <% if current_user.has_profile? %>
      <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
    <% else %>
      <li><%= link_to "Create Profile", new_profile_path %></li>
    <% end %>
    <li><%= link_to "Edit Password", edit_user_registration_path %></li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
  </ul>
</li>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/checkout.html.erb
<% @sum = 0 %>
<% @quantity = 0  %>
<div class="container"><br>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4>Your Cart</h4>
    </div>
    <div class='panel-body'>
      <ol>
      <% if @cart.any? %>
        <div class="row">
          <div class="col-md-1">
          </div>
          <div class="col-md-3">
            <h4>Product</h4>
          </div>
          <div class="col-md-2">
            <h4>Price</h4>
          </div>
          <div class="col-md-2">
            <h4>Quantity</h4>
          </div>
        </div><hr></ol>
        <ol>
          <% @cart.each do |product| %>
            <% @sum += product.price %>
                <div class="row">
                  <li>
                  <div class="col-md-1">
                    <a href = "#" class = "thumbnail">
                      <%= image_tag(product.image) %>
                    </a>
                  </div>
                  <div class="col-md-3">
                    <%= product.title %>
                  </div>
                  <div class="col-md-2">
                    € <%= product.price %>
                  </div>
                  <div class="col-md-2">
                    1
                  </div>
                  <div class="col-md-1">
                    <%= link_to "", cart_path(product), method: :delete, data: {confirm: "Are you sure?"}, class:"glyphicon glyphicon-remove" %>
                  </div>
                </li>
              </div>
          <% end %>
        </ol>
        <hr>
        <p class="col-xs-2">Total price: €<%= @sum %></p>
        <% else %>
        <% end %>
        </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>Please check or update your shipping details below</h4>
      </div>
      <div class='panel-body'>
        <%= render 'form' %>
      </div>
    </div>
  </div>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/index.html.erb
<div class="text-center">
  <div clas="container">
    <br><br>
    <h1 class="header-txt">The Sassy Bookstore</h1>
    <p>Welcome to The Sassy Bookstore - shop all your sassy books here!</p>
    <%= link_to "See all books", products_path, class: "btn btn-default main-btn" %>
  </div>
</div>
<br><hr>
<div class="container text-center">
  <br><br>
  <p id="latestbooks">Latest books</p>
  <br>
  <div class="row">
    <div class="col-xs-4">
      <%= image_tag @product1.image, class: "img-thumbnail" %>
    </div>
    <div class="col-xs-4">
      <%= image_tag @product2.image, class: "img-thumbnail" %>
    </div>
    <div class="col-xs-4">
      <%= image_tag @product3.image, class: "img-thumbnail" %>
    </div>
  </div>
</div>

app/views/pages/thankyou.html.erb
<div class="octo-background">
  <div class="container">
    <div class="row octo-row">
      <img src="http://res.cloudinary.com/maressajoseph/image/upload/v1496411761/octopus1600_gsb7wn.png" class="octo-img">
    </div>
    <div class="row octo-row">
      <h3>Thank you for purchasing 3 octopuses, they will be shipped to you shortly!</h3>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container-fluid">
  <h1 class="text-center">All Books</h1>
</div>
<br><br>
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
          Sort by
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to "Sort A-Z", products_path(sort_by: "Sort A-Z") %></li>
          <li><%= link_to "Sort Z-A", products_path(sort_by: "Sort Z-A") %></li>
          <li><%= link_to "Price low-high", products_path(sort_by: "Price low-high") %></li>
          <li><%= link_to "Price high-low", products_path(sort_by: "Price high-low") %></li>
        </ul>
      </div>
    </div>
    <div class="col-xs-4">
      <%= form_tag(products_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Books by Title", style: ("width:270px") %>
        <%= submit_tag "Search", class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
  <br><br><hr><br>
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-4 text-center">
        <%= image_tag product.image, :class => "img-thumbnail" %>
        <h4 class="text-center"><%= link_to product.title, product %></h4>
        <h5 class="text-center">Price: €<%= product.price %></h5>
        <% if user_signed_in? && current_user.has_profile? %>
          <h4 class="text-center"><%= link_to "", new_product_cart_path(product), class:"glyphicon glyphicon-shopping-cart add-to-cart"%></h4>
        <% end %><br><br>
      </div>
      <% end %>
    <br>
  </div>
</div>

app/views/products/show.html.erb
<div class = "container-fluid"><br>
  <h2 class="text-center"><%= @product.title %> - by <%= @product.author %></h2>
</div>
<br><br><br>
<div class="container">
  <div class="row">
    <div class="col-xs-5 text-right">
      <%= image_tag @product.image, class: "img-thumbnail" %>
    </div>
    <div class="col-xs-6">
      <h3>Book details</h3>
      <hr>
      <h5>Title:  <%= @product.title %></h5>
      <h5>Author: <%= @product.author %></h5>
      <h5>Price: €<%= @product.price %></h5>
      <h5>Description: <%= @product.description %></h5>
      <br>
      <% if user_signed_in? && current_user.has_profile? %>
        <h5><%= link_to "", new_product_cart_path(@product.id), class:"glyphicon glyphicon-shopping-cart"%> Add this book to your shopping cart </h5>
      <% end %>
    </div>
  </div>
  <br><br>
  <nav class="text-center"><%= link_to "Go back to all products", products_path, class: "btn btn-default" %></nav>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Street</label>
    <%= f.text_field :street, placeholder: "Street name + number", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Zip Code</label>
    <%= f.text_field :zipcode, placeholder: "Zip Code", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>City</label>
    <%= f.text_field :city, placeholder: "City", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-success" %>
    <%= link_to "Back", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>